# Issues: None
# Note: Look in /root/waslogs/ for log files and install problems!
#
# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
#
# Attempting to TDS, TIM DB2 DB, TDI, WAS & TIM on one server


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.synced_folder "../software", "/installs"
	
	config.vm.define "tim" do |tim|
		tim.vm.box = "centos65x64chef"
		tim.vm.network "private_network", ip: "10.0.15.2"
		
		tim.vm.provider "virtualbox" do |vb|
			vb.name = "TIM-All_in_one"
			vb.gui = false
			vb.customize ["modifyvm", :id, "--memory", "3072"]
		end
		
		tim.vm.network "forwarded_port", guest: 12100, host: 12100
		tim.vm.network "forwarded_port", guest: 9080, host: 9080
		tim.vm.network "forwarded_port", guest: 80, host: 2080
		tim.vm.network "forwarded_port", guest: 9060, host: 9060
		tim.vm.network "forwarded_port", guest: 9043, host: 9043
		tim.vm.network "forwarded_port", guest: 443, host: 8443	
		tim.vm.network "forwarded_port", guest: 9443, host: 9443
		
		tim.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "../scriptLibrary/cookbooks"
			chef.add_recipe "tdsNode::tds63_x64"
			chef.add_recipe "tdiNode::default"
			chef.add_recipe "WAS::standalone1machine"
		end
	end	
end
