# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centOS_65_i386"

  config.vm.provider "virtualbox" do |vb|
	vb.name = "TDS_i386_V6.1"
	vb.gui = true
  end
  
  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # config.vm.box_url = "http://domain.com/path/to/above.box"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
	config.vm.synced_folder "C:/Users/Dennis English/DownloadDirector/TDS61Linux32", "/installs"
	
  # Provisioning using custom shell script. Custom but will do for now.
    config.vm.provision :shell, :path => "tds_i386_61install.sh"
end