# Issues: None
# Note: Look in /root/waslogs/ for log files and install problems!
#
# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
#


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.synced_folder "../software", "/installs"
	
	config.vm.define "winSrv" do |winSrv|
		winSrv.vm.box = "windows2012"
		winSrv.vm.network "private_network", ip: "10.0.15.30"
		winSrv.vm.provider "virtualbox" do |vb|
			vb.name = "windows2012"
			vb.gui = true
			vb.customize ["modifyvm", :id, "--memory", "1024"]
		end
		
		winSrv.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "../chef/cookbooks"
			chef.environments_path = "../chef/environments"
		#	chef.environment = ""
		#	chef.add_recipe ""
		end
	end

	config.vm.define "winClient" do |winClient|
		winClient.vm.box = "windows7"
		winClient.vm.network "private_network", ip: "10.0.15.31"
		winClient.vm.provider "virtualbox" do |vb|
			vb.name = "windows7"
			vb.gui = true
			vb.customize ["modifyvm", :id, "--memory", "1024"]
		end
		
		winClient.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "../chef/cookbooks"
			chef.environments_path = "../chef/environments"
		#	chef.environment = ""
		#	chef.add_recipe ""
		#	chef.add_recipe ""
		end
	end		
	
end
