# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "precise32"
	config.vm.box_url = "http://files.vagrantup.com/precise32.box"
	config.vm.network "forwarded_port", guest: 8080, host: 1220
	
	config.vm.provision :chef_solo do |chef|
    chef.add_recipe "apt"
#    chef.add_recipe "java"
#    chef.add_recipe "tomcat"
#	chef.add_recipe "openam"

    chef.json.merge!({
                         :java => {
                             :install_flavor => 'openjdk',
                             :jdk_version => '7'
                         }
                     })
	end

	config.vm.provider "virtualbox" do |vb|
		vb.customize ["modifyvm", :id, "--memory", 768]
	end
end
