
DROP TABLE CVDB.LObject;
DROP TABLE CVDB.Name;
DROP TABLE CVDB.CryptoParams;
DROP TABLE CVDB.Link;
DROP TABLE CVDB.AppID;
DROP TABLE CVDB.CustomAttr;
DROP TABLE CVDB.ObjectGroup;
DROP TABLE CVDB.SubjectAN;
DROP TABLE CVDB.DIGEST;
DROP TABLE CVDB.CV_KEYSTORE;
DROP TABLE CVDB.CV_METADATA;

DROP SCHEMA CVDB RESTRICT;
